name = <<[Project Name]>>

# Where to (find | put) stuff
srcdir = src
builddir = build
docdir = docs/generated

# Output
debugbin = $(builddir)/$(name)_debug
releasebin = $(builddir)/$(name)

# How to build
cc = gcc
dbgflags = -g -Wall -Wextra --std=c99 #-fsanitize=address
valgrindflags = --leak-check=full
relflags = -O2 -s

# Don't touch
csrc := $(shell find $(srcdir) -name '*.c')

# Docs are made with `doxygen doxyfile`


###############################################################################
#                                    Rules                                    #
###############################################################################

.PHONY: all debug release run check docs clean cleanall

# Default: build debug and release
all: debug release

# Only debug or release
debug: $(debugbin)
release: $(releasebin)

# Build and run debug executable
run: $(debugbin)
	./$^

# How to build the executables
$(debugbin): $(csrc)
	@mkdir -p $(builddir)
	$(cc) -o $@ $(dbgflags) $^

$(releasebin): $(csrc)
	@mkdir -p $(builddir)
	$(cc) -o $@ $(relflags) $^

# Check with valgrind for memory leaks
check: $(debugbin)
	DEBUGINFO_URLS="https://debuginfod.archlinux.org" \
						valgrind $(valgrindflags) ./$(debugbin)

# Generate documentation
# > Note: The output directory in the doxyfile should correspond to $(docdir)
docs:
	doxygen doxyfile

# Since cleanup removes the $(builddir)
$(builddir):
	@if [ ! -d $(builddir) ]; then mkdir $(builddir); fi

# Clean up
clean:
	rm -fr $(builddir)/ || true

# Clean everything
cleanall:
	rm -fr $(builddir)/ || true
	rm -fr log/** || true
	rm -fr $(docdir) || true
